sudo: required
services:
    - docker
before-install:
    - docker build -t nikhil609651/docker-react -f Dockerfile.dev .

script:
    - docker run nikhil609651/docker-react npm run test -- -- coverage