sudo: required
services:
    - docker
before-install:
    - docker build -t nikhil609651/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true nikhil609651/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-311860729500"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $SECRET_ACCESS_KEY
        
